version: '3.8'

services:
  # PostgreSQL service for the e-learning-monorepo
  elearning_postgres:
    image: postgres
    container_name: elearning_postgres_db_container
    environment:
      POSTGRES_USER: elearning_user # Specific user for the project
      POSTGRES_PASSWORD: elearning_password # Password (in a real environment, use secrets or .env)
      POSTGRES_DB: elearning_main_db # Main database for the e-learning project
    ports:
      - '5432:5432' # Default PostgreSQL port
    volumes:
      - elearning_pg_data:/var/lib/postgresql/data # Volume to persist e-learning data

volumes:
  elearning_pg_data: # Named volume declaration, specific to the PostgreSQL data for e-learning
